import Header from '@/components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/Provider/Provider'
import NavBar from '@/components/NavBar/NavBar.'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
		<html lang='en'>
			<body className={``}>
				<Provider>
					{/* headers    */}
				  <Header />
				  
				  {/* nav bar  */}
				  <NavBar />

					{children}
				</Provider>
			</body>
		</html>
  );
}
